# fly.toml app configuration file generated for twitch-bot-sandesh on 2023-05-26T18:49:42-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "twitch-bot-sandesh"
primary_region = "bos"
kill_signal = "SIGINT"
kill_timeout = "5s"

[env]
  PRIMARY_REGION = "bos"
